name: Check BTC price
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 21
    - name: Getting BTC Price
      id: get-btc-price
      run: |
        BTC_PRICE=$(node ./getBtcPrice.js)
        echo $BTC_PRICE
        echo "btcPrice=$BTC_PRICE" >> $GITHUB_OUTPUT

    - name: send telegram message on BTC lowering
      uses: appleboy/telegram-action@master
      if: steps.get-btc-price.outputs.btcPrice <= 80914
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          BTC price is DOWN: ${{ steps.get-btc-price.outputs.btcPrice }} USD

    - name: send telegram message on BTC rising
      uses: appleboy/telegram-action@master
      if: steps.get-btc-price.outputs.btcPrice >= 82000
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          BTC price is UP: ${{ steps.get-btc-price.outputs.btcPrice }} USD
