name: Check BTC price
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BTC_MIN: 80950
      BTC_ATH: ${{ vars.BTC_ATH }}
      TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 21
    - name: Getting BTC Price
      id: get-btc-price
      run: |
        BTC_PRICE=$(node ./getBtcPrice.js)
        echo "btcPrice=$BTC_PRICE" >> $GITHUB_OUTPUT

        if (( $(echo "$BTC_PRICE > $BTC_ATH" | bc -l) )); then
          echo "New ATH detected: $BTC_PRICE"

          # Update the repository variable via GitHub REST API
          curl -X PATCH \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/actions/variables/BTC_ATH \
            -d "{\"name\":\"BTC_ATH\",\"value\":\"$BTC_PRICE\"}"

          # Update btcAth output for current run
          echo "btcAth=$BTC_PRICE" >> $GITHUB_OUTPUT
        else
          echo "btcAth=$BTC_ATH" >> $GITHUB_OUTPUT
        fi

        echo "Debug: BTC_MIN=$BTC_MIN"
        echo "Debug: BTC_ATH=$BTC_ATH"
        echo "Debug: BTC_CURRENT_PRICE=$BTC_PRICE"

    - name: send telegram message on BTC lowering to minimum
      uses: appleboy/telegram-action@master
      if: steps.get-btc-price.outputs.btcPrice <= env.BTC_MIN
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          [BTC] - !!! WARNING !!! - Lowest price reached - LOSING: ${{ steps.get-btc-price.outputs.btcPrice }} USD

    - name: send telegram message on BTC price
      uses: appleboy/telegram-action@master
      if: steps.get-btc-price.outputs.btcPrice > env.BTC_MIN && steps.get-btc-price.outputs.btcPrice <= steps.get-btc-price.outputs.btcAth
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          [BTC] - Current price: ${{ steps.get-btc-price.outputs.btcPrice }} USD

    - name: send telegram message on BTC rising to ATH
      uses: appleboy/telegram-action@master
      if: steps.get-btc-price.outputs.btcPrice > steps.get-btc-price.outputs.btcAth
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          [BTC] - \o/ New ATH \o/ ===> ${{ steps.get-btc-price.outputs.btcPrice }} USD
